###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /memblog
        volumes:
            - '.:/memblog'
            - './phpdocker/mysql/data/:/docker-entrypoint-initdb.d'
            - './phpdocker/mysql/conf:/etc/my.cnf.d'
        environment:
            - 'MYSQL_ROOT_PASSWORD=root'
            - 'MYSQL_DATABASE=blog_db'
            - 'MYSQL_USER=user'
            - 'MYSQL_PASSWORD=user'
        ports:
            - '8082:3306'
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci 
    webserver:
        image: 'nginx:alpine'
        working_dir: /memblog
        volumes:
            - '.:/memblog'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /memblog
        volumes:
            - '.:/memblog'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
